name: CI

on:
  push:
  pull_request:
  
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Build V
      run: make
    - name: Checkout varekat
      uses: actions/checkout@v2
      with:
        path: varekat
#     - name: V Vet
#      run: ./v vet engine
  
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout varekat
      uses: actions/checkout@v2
      with:
        path: varekat
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --quiet -y libglfw3-dev libvulkan-dev
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: Verify fmt
      run: |
        cd varekat
        v run fmt.vsh verify
    - name: Build varekat
      run: |
        cd varekat
        v .
